apiVersion: v1
kind: Service
metadata:
  name: stratomesh-frontend
  namespace: stratomesh
spec:
  type: ClusterIP
  selector:
    app: stratomesh-frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
